import { Project } from '@/types'
import { getCDNUrl, getProjectImageUrl, getProjectThumbnailUrl, getCroquisUrl } from './cdn'

export const projects: Project[] = [
  // Viviendas Unifamiliares
  {
    slug: 'casa-ga',
    name: 'Casa GA',
    category: 'vivienda',
    description: 'Vivienda unifamiliar en Mendoza',
    heroImage: getCDNUrl('projects/casa-ga/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-ga'),
    gallery: [
      // Primera columna - 15 imágenes
      getProjectImageUrl('casa-ga', 'GA-1.webp'),
      getProjectImageUrl('casa-ga', 'GA-2.webp'),
      getProjectImageUrl('casa-ga', 'GA-3.webp'),
      getProjectImageUrl('casa-ga', 'GA-4.webp'),
      getProjectImageUrl('casa-ga', 'GA-5.webp'),
      getProjectImageUrl('casa-ga', 'GA-6.webp'),
      getProjectImageUrl('casa-ga', 'GA-49.webp'),
      getProjectImageUrl('casa-ga', 'GA-8.webp'),
      getProjectImageUrl('casa-ga', 'GA-50.webp'),
      getProjectImageUrl('casa-ga', 'GA-10.webp'),
      getProjectImageUrl('casa-ga', 'GA-11.webp'),
      getProjectImageUrl('casa-ga', 'GA-12.webp'),
      getProjectImageUrl('casa-ga', 'GA-13.webp'),
      getProjectImageUrl('casa-ga', 'GA-14.webp'),
      getProjectImageUrl('casa-ga', 'GA-15.webp'),
      // Segunda columna - 15 imágenes
      getProjectImageUrl('casa-ga', 'GA-16.webp'),
      getProjectImageUrl('casa-ga', 'GA-17.webp'),
      getProjectImageUrl('casa-ga', 'GA-18.webp'),
      getProjectImageUrl('casa-ga', 'GA-19.webp'),
      getProjectImageUrl('casa-ga', 'GA-20.webp'),
      getProjectImageUrl('casa-ga', 'GA-21.webp'),
      getProjectImageUrl('casa-ga', 'GA-22.webp'),
      getProjectImageUrl('casa-ga', 'GA-23.webp'),
      getProjectImageUrl('casa-ga', 'GA-46.webp'),
      getProjectImageUrl('casa-ga', 'GA-47.webp'),
      getProjectImageUrl('casa-ga', 'GA-51.webp'),
      getProjectImageUrl('casa-ga', 'GA-27.webp'),
      getProjectImageUrl('casa-ga', 'GA-28.webp'),
      getProjectImageUrl('casa-ga', 'GA-29.webp'),
      getProjectImageUrl('casa-ga', 'GA-30.webp'),
      // Tercera columna - 15 imágenes
      getProjectImageUrl('casa-ga', 'GA-31.webp'),
      getProjectImageUrl('casa-ga', 'GA-32.webp'),
      getProjectImageUrl('casa-ga', 'GA-33.webp'),
      getProjectImageUrl('casa-ga', 'GA-34.webp'),
      getProjectImageUrl('casa-ga', 'GA-35.webp'),
      getProjectImageUrl('casa-ga', 'GA-36.webp'),
      getProjectImageUrl('casa-ga', 'GA-37.webp'),
      getProjectImageUrl('casa-ga', 'GA-38.webp'),
      getProjectImageUrl('casa-ga', 'GA-39.webp'),
      getProjectImageUrl('casa-ga', 'GA-40.webp'),
      getProjectImageUrl('casa-ga', 'GA-41.webp'),
      getProjectImageUrl('casa-ga', 'GA-42.webp'),
      getProjectImageUrl('casa-ga', 'GA-43.webp'),
      getProjectImageUrl('casa-ga', 'GA-44.webp'),
      getProjectImageUrl('casa-ga', 'GA-45.webp'),
    ],
    featured: true,
  },
  {
    slug: 'casa-vl',
    name: 'Casa VL',
    category: 'vivienda',
    description: 'Casa Atelier',
    heroImage: getCDNUrl('projects/casa-vl/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-vl'),
    gallery: [
      getProjectImageUrl('casa-vl', 'VL-1.webp'),
      getProjectImageUrl('casa-vl', 'VL-2.webp'),
      getProjectImageUrl('casa-vl', 'VL-3.webp'),
      getProjectImageUrl('casa-vl', 'VL-4.webp'),
      getProjectImageUrl('casa-vl', 'VL-15.webp'),
      getProjectImageUrl('casa-vl', 'VL-6.webp'),
      getProjectImageUrl('casa-vl', 'VL-21.webp'),
      getProjectImageUrl('casa-vl', 'VL-20.webp'),
      getProjectImageUrl('casa-vl', 'VL-8.webp'),
      getProjectImageUrl('casa-vl', 'VL-9.webp'),
      getProjectImageUrl('casa-vl', 'VL-10.webp'),
      getProjectImageUrl('casa-vl', 'VL-11.webp'),
      getProjectImageUrl('casa-vl', 'VL-12.webp'),
      getProjectImageUrl('casa-vl', 'VL-25.webp'),
      getProjectImageUrl('casa-vl', 'VL-13.webp'),
      getProjectImageUrl('casa-vl', 'VL-23.webp'),
      getProjectImageUrl('casa-vl', 'VL-5.webp'),
      getProjectImageUrl('casa-vl', 'VL-16.webp'),
      getProjectImageUrl('casa-vl', 'VL-17.webp'),
      getProjectImageUrl('casa-vl', 'VL-24.webp'),
    ],
    featured: true,
  },
  {
    slug: 'bendita-piedra',
    name: 'Bendita Piedra',
    category: 'inmobiliario',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/bendita-piedra/hero.webp'),
    thumbnail: getProjectThumbnailUrl('bendita-piedra'),
    gallery: [
      getProjectImageUrl('bendita-piedra', 'BP-1.webp'),
      getProjectImageUrl('bendita-piedra', 'BP-2.webp'),
      getProjectImageUrl('bendita-piedra', 'BP-11.webp'),
      getProjectImageUrl('bendita-piedra', 'BP-15.webp'),
      getProjectImageUrl('bendita-piedra', 'BP-22.webp'),
      getProjectImageUrl('bendita-piedra', 'BP-5.webp'),
      getProjectImageUrl('bendita-piedra', 'BP-4.webp'),
      getProjectImageUrl('bendita-piedra', 'BP-8.webp'),
      getProjectImageUrl('bendita-piedra', 'BP-22.webp'),
      getProjectImageUrl('bendita-piedra', 'BP-9.webp'),
      getProjectImageUrl('bendita-piedra', 'BP-10.webp'),
      getProjectImageUrl('bendita-piedra', 'BP-3.webp'),
      getProjectImageUrl('bendita-piedra', 'BP-20.webp'),
    ],
    featured: true,
  },
  {
    slug: 'casa-bac',
    name: 'Casa BAC',
    category: 'vivienda',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/casa-bac/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-bac'),
    gallery: [
      getProjectImageUrl('casa-bac', 'BAC-4.webp'),
      getProjectImageUrl('casa-bac', 'BAC-2.webp'),
      getProjectImageUrl('casa-bac', 'BAC-3.webp'),
      getProjectImageUrl('casa-bac', 'BAC-5.webp'),
      getProjectImageUrl('casa-bac', 'BAC-10.webp'),
      getProjectImageUrl('casa-bac', 'BAC-6.webp'),
      getProjectImageUrl('casa-bac', 'BAC-7.webp'),
      getProjectImageUrl('casa-bac', 'BAC-8.webp'),
      getProjectImageUrl('casa-bac', 'BAC-9.webp'),
    ],
  },
  {
    slug: 'casa-sm',
    name: 'Casa SM',
    category: 'vivienda',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/casa-sm/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-sm'),
    gallery: [
      getProjectImageUrl('casa-sm', 'SM-5.webp'),
      getProjectImageUrl('casa-sm', 'SM-1.webp'),
      getProjectImageUrl('casa-sm', 'SM-3.webp'),
      getProjectImageUrl('casa-sm', 'SM-4.webp'),
      getProjectImageUrl('casa-sm', 'SM-2.webp'),
      getProjectImageUrl('casa-sm', 'SM-8.webp'),
      getProjectImageUrl('casa-sm', 'SM-6.webp'),
    ],
  },
  {
    slug: 'casa-ferm',
    name: 'Casa FERM',
    category: 'vivienda',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/casa-ferm/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-ferm'),
    gallery: [
      getProjectImageUrl('casa-ferm', 'FM-1.webp'),
      getProjectImageUrl('casa-ferm', 'FM-2.webp'),
      getProjectImageUrl('casa-ferm', 'FM-3.webp'),
      getProjectImageUrl('casa-ferm', 'FM-9.webp'),
      getProjectImageUrl('casa-ferm', 'FM-5.webp'),
      getProjectImageUrl('casa-ferm', 'FM-7.webp'),
      getProjectImageUrl('casa-ferm', 'FM-8.webp'),
      getProjectImageUrl('casa-ferm', 'FM-10.webp'),
    ],
  },
  {
    slug: 'casa-fdm',
    name: 'Casa FDM',
    category: 'vivienda',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/casa-fdm/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-fdm'),
    gallery: [
      getProjectImageUrl('casa-fdm', 'FDM-1.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-2.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-3.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-10.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-11.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-16.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-4.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-5.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-6.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-12.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-13.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-18.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-19.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-7.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-8.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-9.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-15.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-14.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-20.webp'),
      getProjectImageUrl('casa-fdm', 'FDM-21.webp'),
    ],
    featured: true,
  },
  {
    slug: 'casa-ha',
    name: 'Casa HA',
    category: 'vivienda',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/casa-ha/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-ha'),
    gallery: [
      getProjectImageUrl('casa-ha', 'HA-1.webp'),
      getProjectImageUrl('casa-ha', 'HA-2.webp'),
      getProjectImageUrl('casa-ha', 'HA-6.webp'),
      getProjectImageUrl('casa-ha', 'HA-4.webp'),
      getProjectImageUrl('casa-ha', 'HA-7.webp'),
      getProjectImageUrl('casa-ha', 'HA-8.webp'),
    ],
  },
  {
    slug: 'casa-per',
    name: 'Casa PER',
    category: 'vivienda',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/casa-per/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-per'),
    gallery: [
      getProjectImageUrl('casa-per', 'casaPER-1.webp'),
      getProjectImageUrl('casa-per', 'casaPER-2.webp'),
      getProjectImageUrl('casa-per', 'casaPER-3.webp'),
      getProjectImageUrl('casa-per', 'casaPER-4.webp'),
      getProjectImageUrl('casa-per', 'casaPER-5.webp'),
      getProjectImageUrl('casa-per', 'casaPER-6.webp'),
    ],
  },
  {
    slug: 'casa-manz',
    name: 'Casa MANZ',
    category: 'vivienda',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/casa-manz/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-manz'),
    gallery: [
      getProjectImageUrl('casa-manz', 'man-1.webp'),
      getProjectImageUrl('casa-manz', 'man-2.webp'),
      getProjectImageUrl('casa-manz', 'man-10.webp'),
      getProjectImageUrl('casa-manz', 'man-4.webp'),
      getProjectImageUrl('casa-manz', 'man-5.webp'),
      getProjectImageUrl('casa-manz', 'man-6.webp'),
      getProjectImageUrl('casa-manz', 'man-7.webp'),
      getProjectImageUrl('casa-manz', 'man-8.webp'),
      getProjectImageUrl('casa-manz', 'man-9.webp'),
    ],
  },
  {
    slug: 'casa-am',
    name: 'Casa AM',
    category: 'vivienda',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/casa-am/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-am'),
    gallery: [
      getProjectImageUrl('casa-am', 'AM-1.webp'),
      getProjectImageUrl('casa-am', 'AM-2.webp'),
      getProjectImageUrl('casa-am', 'AM-3.webp'),
      getProjectImageUrl('casa-am', 'AM-10.webp'),
      getProjectImageUrl('casa-am', 'AM-13.webp'),
      getProjectImageUrl('casa-am', 'AM-4.webp'),
      getProjectImageUrl('casa-am', 'AM-6.webp'),
      getProjectImageUrl('casa-am', 'AM-12.webp'),
      getProjectImageUrl('casa-am', 'AM-7.webp'),
      getProjectImageUrl('casa-am', 'AM-8.webp'),
      getProjectImageUrl('casa-am', 'AM-9.webp'),
      getProjectImageUrl('casa-am', 'AM-11.webp'),
    ],
  },
  {
    slug: 'casa-al',
    name: 'Casa AL',
    category: 'vivienda',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/casa-al/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-al'),
    gallery: [
      getProjectImageUrl('casa-al', 'AL-2.webp'),
      getProjectImageUrl('casa-al', 'AL-3.webp'),
      getProjectImageUrl('casa-al', 'AL-1.webp'),
      getProjectImageUrl('casa-al', 'AL-4.webp'),
    ],
  },
  {
    slug: 'casa-na',
    name: 'Casa NA',
    category: 'vivienda',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/casa-na/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-na'),
    gallery: [
      getProjectImageUrl('casa-na', 'casaNA-1.webp'),
      getProjectImageUrl('casa-na', 'casaNA-2.webp'),
      getProjectImageUrl('casa-na', 'casaNA-3.webp'),
      getProjectImageUrl('casa-na', 'casaNA-5.webp'),
      getProjectImageUrl('casa-na', 'casaNA-4.webp'),
      getProjectImageUrl('casa-na', 'casaNA-8.webp'),
      getProjectImageUrl('casa-na', 'casaNA-9.webp'),
      getProjectImageUrl('casa-na', 'casaNA-10.webp'),
      getProjectImageUrl('casa-na', 'casaNA-11.webp'),
      getProjectImageUrl('casa-na', 'casaNA-33.webp'),
      getProjectImageUrl('casa-na', 'casaNA-12.webp'),
      getProjectImageUrl('casa-na', 'casaNA-13.webp'),
      getProjectImageUrl('casa-na', 'casaNA-14.webp'),
      getProjectImageUrl('casa-na', 'casaNA-15.webp'),
      getProjectImageUrl('casa-na', 'casaNA-16.webp'),
      getProjectImageUrl('casa-na', 'casaNA-17.webp'),
      getProjectImageUrl('casa-na', 'casaNA-18.webp'),
      getProjectImageUrl('casa-na', 'casaNA-19.webp'),
      getProjectImageUrl('casa-na', 'casaNA-20.webp'),
      getProjectImageUrl('casa-na', 'casaNA-21.webp'),
      getProjectImageUrl('casa-na', 'casaNA-22.webp'),
      getProjectImageUrl('casa-na', 'casaNA-6.webp'),
      getProjectImageUrl('casa-na', 'casaNA-7.webp'),
      getProjectImageUrl('casa-na', 'casaNA-23.webp'),
      getProjectImageUrl('casa-na', 'casaNA-24.webp'),
      getProjectImageUrl('casa-na', 'casaNA-25.webp'),
      getProjectImageUrl('casa-na', 'casaNA-26.webp'),
      getProjectImageUrl('casa-na', 'casaNA-27.webp'),
      getProjectImageUrl('casa-na', 'casaNA-28.webp'),
      getProjectImageUrl('casa-na', 'casaNA-29.webp'),
      getProjectImageUrl('casa-na', 'casaNA-30.webp'),
      getProjectImageUrl('casa-na', 'casaNA-31.webp'),
      getProjectImageUrl('casa-na', 'casaNA-32.webp'),
    ],
  },
  {
    slug: 'casa-pm',
    name: 'Casa PM',
    category: 'vivienda',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/casa-pm/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-pm'),
    gallery: [
      getProjectImageUrl('casa-pm', 'casaPM-1.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-3.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-2.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-4.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-5.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-9.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-6.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-7.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-8.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-11.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-12.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-13.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-14.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-15.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-10.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-16.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-17.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-18.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-19.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-20.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-21.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-32.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-22.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-23.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-24.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-25.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-39.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-26.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-27.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-28.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-29.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-30.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-31.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-33.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-34.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-35.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-36.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-37.webp'),
      getProjectImageUrl('casa-pm', 'casaPM-38.webp'),
    ],
  },
  {
    slug: 'casa-gp',
    name: 'Casa GP',
    category: 'vivienda',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/casa-gp/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-gp'),
    gallery: [
      getProjectImageUrl('casa-gp', 'POT-1.webp'),
      getProjectImageUrl('casa-gp', 'POT-3.webp'),
      getProjectImageUrl('casa-gp', 'POT-2.webp'),
      getProjectImageUrl('casa-gp', 'POT-1.webp'),
    ],
  },
  {
    slug: 'casa-camp',
    name: 'Casa CAMP',
    category: 'vivienda',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/casa-camp/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-camp'),
    gallery: [
      getProjectImageUrl('casa-camp', 'casaCAMP-3.webp'),
      getProjectImageUrl('casa-camp', 'casaCAMP-2.webp'),
      getProjectImageUrl('casa-camp', 'casaCAMP-4.webp'),
      getProjectImageUrl('casa-camp', 'casaCAMP-5.webp'),
      getProjectImageUrl('casa-camp', 'casaCAMP-6.webp'),
    ],
  },
  {
    slug: 'casa-aa',
    name: 'Casa AA',
    category: 'vivienda',
    description: 'Vivienda unifamiliar',
    heroImage: getCDNUrl('projects/casa-aa/hero.webp'),
    thumbnail: getProjectThumbnailUrl('casa-aa'),
    gallery: [
      getProjectImageUrl('casa-aa', 'AA-1.webp'),
      getProjectImageUrl('casa-aa', 'AA-2.webp'),
      getProjectImageUrl('casa-aa', 'AA-3.webp'),
      getProjectImageUrl('casa-aa', 'AA-4.webp'),
      getProjectImageUrl('casa-aa', 'AA-5.webp'),
      getProjectImageUrl('casa-aa', 'AA-6.webp'),
      getProjectImageUrl('casa-aa', 'AA-7.webp'),
      getProjectImageUrl('casa-aa', 'AA-11.webp'),
      getProjectImageUrl('casa-aa', 'AA-8.webp'),
      getProjectImageUrl('casa-aa', 'AA-9.webp'),
      getProjectImageUrl('casa-aa', 'AA-10.webp'),
    ],
    featured: true,
  },

  // Complejos Residenciales
  {
    slug: 'edificio-catalan',
    name: 'Edificio Catalan',
    category: 'complejos',
    description: 'Complejo residencial',
    heroImage: getCDNUrl('projects/edificio-catalan/hero.webp'),
    thumbnail: getProjectThumbnailUrl('edificio-catalan'),
    gallery: [
      getProjectImageUrl('edificio-catalan', 'CAT-1.webp'),
      getProjectImageUrl('edificio-catalan', 'CAT-2.webp'),
      getProjectImageUrl('edificio-catalan', 'CAT-3.webp'),
      getProjectImageUrl('edificio-catalan', 'CAT-7.webp'),
      getProjectImageUrl('edificio-catalan', 'CAT-5.webp'),
      getProjectImageUrl('edificio-catalan', 'CAT-6.webp'),
      getProjectImageUrl('edificio-catalan', 'CAT-8.webp'),
      getProjectImageUrl('edificio-catalan', 'CAT-9.webp'),
      getProjectImageUrl('edificio-catalan', 'CAT-10.webp'),
      getProjectImageUrl('edificio-catalan', 'CAT-11.webp'),
    ],
  },
  {
    slug: 'deptos-urquiza',
    name: 'Deptos Urquiza',
    category: 'complejos',
    description: 'Complejo residencial',
    heroImage: getCDNUrl('projects/deptos-urquiza/hero.webp'),
    thumbnail: getProjectThumbnailUrl('deptos-urquiza'),
    gallery: [
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-1.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-2.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-6.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-7.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-16.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-17.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-18.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-10.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-11.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-12.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-13.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-14.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-9.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-8.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-24.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-15.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-21.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-22.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-20.webp'),
      getProjectImageUrl('deptos-urquiza', 'DeptUrq-19.webp'),
    ],
  },
  {
    slug: 'piedra-escondida',
    name: 'Piedra Escondida',
    category: 'complejos',
    description: 'Complejo residencial',
    heroImage: getCDNUrl('projects/piedra-escondida/hero.webp'),
    thumbnail: getProjectThumbnailUrl('piedra-escondida'),
    gallery: [
      getProjectImageUrl('piedra-escondida', 'PE-1.webp'),
      getProjectImageUrl('piedra-escondida', 'PE-2.webp'),
      getProjectImageUrl('piedra-escondida', 'PE-3.webp'),
      getProjectImageUrl('piedra-escondida', 'PE-4.webp'),
      getProjectImageUrl('piedra-escondida', 'PE-5.webp'),
      getProjectImageUrl('piedra-escondida', 'PE-6.webp'),
      getProjectImageUrl('piedra-escondida', 'PE-7.webp'),
      getProjectImageUrl('piedra-escondida', 'PE-8.webp'),
      getProjectImageUrl('piedra-escondida', 'PE-9.webp'),
      getProjectImageUrl('piedra-escondida', 'PE-10.webp'),
      getProjectImageUrl('piedra-escondida', 'PE-11.webp'),
      getProjectImageUrl('piedra-escondida', 'PE-12.webp'),
      getProjectImageUrl('piedra-escondida', 'PE-13.webp'),
    ],
  },
  {
    slug: 'via-pergola',
    name: 'Vía Pérgola',
    category: 'complejos',
    description: 'Complejo residencial',
    heroImage: getCDNUrl('projects/via-pergola/hero.webp'),
    thumbnail: getProjectThumbnailUrl('via-pergola'),
    gallery: [
      getProjectImageUrl('via-pergola', 'ViaP-1.webp'),
      getProjectImageUrl('via-pergola', 'viaP-10.webp'),
      getProjectImageUrl('via-pergola', 'ViaP-4.webp'),
      getProjectImageUrl('via-pergola', 'ViaP-5.webp'),
      getProjectImageUrl('via-pergola', 'ViaP-8.webp'),
    ],
  },

  // Desarrollos Inmobiliarios
  {
    slug: 'la-bajada',
    name: 'La Bajada',
    category: 'inmobiliario',
    description: 'Desarrollo inmobiliario',
    heroImage: getCDNUrl('projects/la-bajada/hero.webp'),
    thumbnail: getProjectThumbnailUrl('la-bajada'),
    gallery: [
      getProjectImageUrl('la-bajada', 'BAJADAMALL-1.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-3.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-18.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-14.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-15.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-21.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-28.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-4.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-8.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-7.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-16.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-17.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-23.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-24.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-25.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-10.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-11.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-9.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-20.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-19.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-26.webp'),
      getProjectImageUrl('la-bajada', 'BAJADAMALL-27.webp'),
    ],
  },
]

// Croquis como items separados
export const croquis = Array.from({ length: 18 }, (_, i) => ({
  slug: `croquis-${i + 1}`,
  name: `Croquis ${i + 1}`,
  category: 'croquis' as const,
  description: 'Boceto arquitectónico',
  heroImage: getCroquisUrl(`croquis-${i + 1}.png`),
  thumbnail: getCroquisUrl(`croquis-${i + 1}.png`),
  gallery: [],
  featured: false
}))

const allProjects = [...projects, ...croquis]

export async function getAllProjects(): Promise<Project[]> {
  return allProjects
}

export async function getProjectBySlug(slug: string): Promise<Project | undefined> {
  return allProjects.find((p) => p.slug === slug)
}

export async function getProjectsByCategory(category: string): Promise<Project[]> {
  if (category === 'all') return projects
  return projects.filter((p) => p.category === category)
}

export async function getFeaturedProjects(): Promise<Project[]> {
  return projects.filter((p) => p.featured)
}

export const categories = [
  { value: 'all', label: 'Todas' },
  { value: 'vivienda', label: 'Viviendas Unifamiliares' },
  { value: 'inmobiliario', label: 'Desarrollos Inmobiliarios' },
  { value: 'complejos', label: 'Complejos Residenciales' },
  { value: 'croquis', label: 'Croquis' },
]